# Generated by Django 2.1.2 on 2018-11-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField(default=None)),
                ('floor_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('number', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configure.Floor')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('roomtype_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('desc', models.TextField()),
                ('type_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configure.RoomType'),
        ),
    ]
