# Generated by Django 2.1.2 on 2018-11-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('number', models.IntegerField(auto_created=True, max_length=100, primary_key=True, serialize=False)),
                ('floor', models.IntegerField(default=None, max_length=2)),
                ('room_type', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
