# Generated by Django 2.1.2 on 2018-11-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='floor',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
