# Generated by Django 2.1.2 on 2018-11-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20181109_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField(default=None)),
                ('floor_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=10)),
                ('rate', models.IntegerField()),
                ('desc', models.TextField()),
                ('type_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='rooms',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Floor'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.RoomType'),
        ),
    ]
