# Generated by Django 2.1.2 on 2018-11-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20181111_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor_number',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
