# Generated by Django 2.1.2 on 2018-11-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20181111_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='id',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
