# Generated by Django 2.1.2 on 2018-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20181111_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='type_id',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
